### ISSUE TITLE
Turn user-api into kafka message producer

### ISSUE THREAD

**Issue by fridex** [thoth-station/user-api#1028]
**Is your feature request related to a problem? Please describe.**

Currently, user-api schedules directly workflows for adviser, provenance-check and image analyzes. We should let the investigator to schedule workflows. This way we will be prone to DoS attacks (kafka will hold the messages, not kubernetes' etcd which can go haywire in such cases).

**Describe the solution you'd like**

Turn user-api into kafka producer.

1. create corresponding messages in thoth-messaging
2. each time there is done a request to user-api, it results in a new message being published instead of directly scheduling Argo workflows
3. investigator is extended in a way it can handle messages for scheduling respective Argo workflows.
4. this procedure can be also applied to management-api

**Comment by pacospace** [comment]
what about the status of an adviser workflow?

Maybe we could reuse the `onexit` from workflows to know the status or send messages about ScheduledWorkflow with status after scheduling a workflow and inside the workflow having another message send from a task that is sent back to say if the workflow succeeded or failed. Otherwise it will be still in progress for the user. 
Maybe this can work for Qeb-Hwt so the time shown in a PR does not go to infinite if adviser failed.

**Comment by fridex** [comment]
> Nice!! What about the status of an adviser workflow?
> 
> Maybe we could reuse the `onexit` from workflows to know the status or send messages about ScheduledWorkflow with status after scheduling a workflow and inside the workflow having another message send from a task that is sent back to say if the workflow succeeded or failed. Otherwise it will be still in progress for the user.
> Maybe this can work for Qeb-Hwt so the time shown in a PR does not go to infinite if adviser failed.

IMHO obtaining status can work as-is for workflows. Once the message is published to the broker, we know the system will consume the message and respond to it. The only "empty space" is between publishing the message and consuming it - we can mark the request on ceph (we will need to do it anyway to keep logs).

**Comment by pacospace** [comment]
@KPostOffice made user-api a Kafka producer: https://github.com/thoth-station/user-api/pull/1063
