### ISSUE TITLE
User Api gives Internal Server Error 

### ISSUE THREAD

**Issue by saisankargochhayat** [thoth-station/user-api#1085]
To replicate error - `curl -X GET "https://khemenu.thoth-station.ninja/api/v1/advise/python/adviser-ae329d5b" -H  "accept: application/json"`
Or from swagger api try fetching advise for - `adviser-ae329d5b`
Log from the cluster - https://paste.ofcode.org/Nw3DnJ9Sk2FEUCMiEvu7g7
Expected behaviour - should give advise result if found else 404 if they aren't ready or 202 if advise is running

**Comment by fridex** [comment]
/assign @saisankargochhayat 

Sai did the fix for this :+1:

**Comment by saisankargochhayat** [comment]
Going to close this
