### ISSUE TITLE
Return correct status for adviser run

### ISSUE THREAD

**Issue by bissenbay** [thoth-station/user-api#1092]
**Describe the bug**
When a simple thamos advice is scheduled, this endpoint `/advise/python/{analysis_id}/status` returns `running` state, even though one of the tasks is already failed.

**To Reproduce**
1. Run `THOTH_USER_API_HOST=test.thoth-station.ninja THOTH_MANAGEMENT_API_HOST=management.test.thoth-station.ninja pipenv run behave -i features/thamos_advise.feature` in `integration-tests`.
2. Go to http://argo-ui-thoth-test-core.apps.ocp.prod.psi.redhat.com/workflows/thoth-test-core/ and choose the adviser workflow which is scheduled recently.
3. See error

**Options**
1. Wait the workflow to be finished and at the end return `failed`, it might take very long time, like hours.
2. Maybe occasionally check status of each steps of the workflow and if notice that some of the tasks failed, then return `failed` right away instead of waiting for the whole workflow to be finished.

Related-To: https://github.com/thoth-station/integration-tests/issues/36

**Comment by fridex** [comment]
Check `get_workflow_node_log`:

https://github.com/thoth-station/common/blob/fd1229305a1dcaabe51eecbb290887bd1ccdf7d5/thoth/common/openshift.py#L380-L393

We can follow the same pattern - introduce a function  `get_workflow_node_status` and provide node name in the workflow that should be checked for status. This function should live directly in thoth-common.

**Comment by bissenbay** [comment]
@fridex I found this medthod https://github.com/thoth-station/common/blob/fd1229305a1dcaabe51eecbb290887bd1ccdf7d5/thoth/common/openshift.py#L487, I wonder if I can use it inside `get_workflow_node_status`, if yes, where I can get `pod_id`?
