### ISSUE TITLE
Update openapi.json file with relevant changes to fix thamos regeneration pre-commit issues.

### ISSUE THREAD

**Issue by harshad16** [thoth-station/user-api#1110]
**Is your feature request related to a problem? Please describe.**
`thamos` client files are updated with swagger-client regeneration script which pulls changes into python content from the user-api open API JSON file. some of the autogenerated code causes failure of pre-commit checks. 
as this step is repeated whenever we want to pull new changes of user-api into thamos, this issue would occur again even if fixed at thamos side once. 

such as: 
```
thamos/swagger_client/models/python_platforms.py:31: error: Need type annotation for 'swagger_types' (hint: "swagger_types: Dict[<type>, <type>] = ...")
thamos/swagger_client/models/python_platforms.py:34: error: Need type annotation for 'attribute_map' (hint: "attribute_map: Dict[<type>, <type>] = ...")
thamos/swagger_client/models/python_package_dependencies.py:31: error: Need type annotation for 'swagger_types' (hint: "swagger_types: Dict[<type>, <type>] = ...")
thamos/swagger_client/models/python_package_dependencies.py:34: error: Need type annotation for 'attribute_map' (hint: "attribute_map: Dict[<type>, <type>] = ...")
thamos/swagger_client/models/python_package_indexes.py:31: error: Need type annotation for 'swagger_types' (hint: "swagger_types: Dict[<type>, <type>] = ...")
thamos/swagger_client/models/python_package_indexes.py:34: error: Need type annotation for 'attribute_map' (hint: "attribute_map: Dict[<type>, <type>] = ...")
thamos/swagger_client/models/kebechet_webhook_input.py:31: error: Need type annotation for 'swagger_types' (hint: "swagger_types: Dict[<type>, <type>] = ...")
thamos/swagger_client/models/kebechet_webhook_input.py:34: error: Need type annotation for 'attribute_map' (hint: "attribute_map: Dict[<type>, <type>] = ...")
thamos/swagger_client/api_client.py:53: error: Name 'long' is not defined
Found 9 errors in 5 files (checked 65 source files)
```

**Describe the solution you'd like**
Feels like this should be fixed at the user-api side, so it doesn't occur repeatedly and we wouldn't have to exclude file in pre-commit-config file for thamos.

**Describe alternatives you've considered**
Exclude client file from pre-commit-config file on thamos side to exclude from such repeated pre-commit check failure.

**Additional context**
https://github.com/thoth-station/thamos/pull/553
https://github.com/thoth-station/thamos/issues/540

**Comment by fridex** [comment]
> **Describe the solution you'd like**
> Feels like this should be fixed at the user-api side, so it doesn't occur repeatedly and we wouldn't have to exclude file in pre-commit-config file for thamos.

It's not clear to me how this is related to user-api. Are these errors related to thamos repo and the autogenerated code that is not compliant with pre-commit config file?

**Comment by saisankargochhayat** [comment]
> Exclude client file from pre-commit-config file on thamos side to exclude from such repeated pre-commit check failure.
  The alternative seems like the way to go forward. The thamos autogenerated files should be ignored by pre-commit and we should only fix pre-commit for the developer written code.

**Comment by harshad16** [comment]
> It's not clear to me how this is related to user-api. Are these errors related to thamos repo and the autogenerated code that is not compliant with pre-commit config file?

These errors occurring on the autogenerated code that is not compliant with pre-commit config file. 
While creating autogenerated code from a few of the endpoint reference in the openapi json file, the pre-commit is failing on them.
I was thinking _maybe_ we could try to fix them in here, if possible then we would not have to ignore them in pre-commit.
this could be a learning experience.

**Comment by fridex** [comment]
> > It's not clear to me how this is related to user-api. Are these errors related to thamos repo and the autogenerated code that is not compliant with pre-commit config file?
> 
> These errors occurring on the autogenerated code that is not compliant with pre-commit config file.

This code lives in thamos repo - that's why I'm not sure if I follow this issue reported to user-api repo.

> While creating autogenerated code from a few of the endpoint reference in the openapi json file, the pre-commit is failing on them.
> I was thinking **_maybe_** we could try to fix them in here, if possible then we would not have to ignore them in pre-commit.
> this could be a learning experience.

To my understanding, the client code is generated in thamos repo and it lives in the thamos repo. That's why we experience pre-commit issues in the thamos repo. I haven't spotted any pre-commit issues in this repo, please correct me if I missed something.

**Comment by harshad16** [comment]
Ack, I agree that client code is generated in thamos repo, however, the code is generated based upon the schema defined in the [openapi.yaml](https://github.com/thoth-station/user-api/blob/master/openapi/openapi.yaml), what I feel is the properties in the component part of YAML for the specific endpoint causing the issue can be tweaked (if possible) to away such that the code compliance with pre-commit when auto code generation is done.
If this is still not clear let me know, I would look at this and create an example or pull request to do the changes based on this.

**Comment by fridex** [comment]
> If this is still not clear let me know, I would look at this and create an example or pull request to do the changes based on this.

I will need some help here to understand this. The errors reported (shown in the issue description) are on Python code level, not on openapi.yaml. Hence it's not clear to me what issue are we trying to solve here.

**Comment by fridex** [comment]
I don't see this relevant anymore. Closing. Fee free to reopen if the issue persists.

Thanks! :+1:
