### ISSUE TITLE
Create endpoints serving information about packages analyzed

### ISSUE THREAD

**Issue by fridex** [thoth-station/user-api#1112]
**Is your feature request related to a problem? Please describe.**

As Thoth user, I would like to get information about the data Thoth keeps in its knowledge base and possibly visualize them in a nice UI so that I can see what observations Thoth can provide me. The goal of this task is to create endpoints, each serving requests for a specific package in version so data are exposed and can be visualized in a UI. An example could be:

```
/python/package/security
/python/package/solvers
```

The example follows metadata endpoint we already have. We can redesign it to have URLs similar to PyPI URLs.

These endpoints could reveal information about the given package so a nice UI webpage can be used to visualize the data (e.g. a table of runtime environments where the given package is installable).

**Comment by goern** [comment]
@fridex is this something that @Gkrumbach07 could use?!

**Comment by fridex** [comment]
> @fridex is this something that @Gkrumbach07 could use?!

For the license part, we will need to create an endpoint based on @meile18 license detection algorithm.

**Comment by fridex** [comment]
And the dependency structure information is discussed in https://github.com/thoth-station/user-api/issues/1471

**Comment by goern** [comment]
is https://github.com/thoth-station/thoth-application/issues/1496 related?

**Comment by fridex** [comment]
> is [thoth-station/thoth-application#1496](https://github.com/thoth-station/thoth-application/issues/1496) related?

yes
