### ISSUE TITLE
Consider removing endpoints listing requests (e.g. /python/advise)

### ISSUE THREAD

**Issue by fridex** [thoth-station/user-api#1139]
**Is your feature request related to a problem? Please describe.**

Let's consider if we want to keep endpoints that list analyses on Thoth side. If we keep them, users can browse all the requests were done.

**Comment by goern** [comment]
I like it, it seems to be a security measure we should implement, right?

/kind feature
/priority important-soon

**Comment by saisankargochhayat** [comment]
Do we want to remove the endpoints and still have the methods? Or just remove them?

**Comment by goern** [comment]
I would make it minimal invasive: just the API endpoint removed

**Comment by fridex** [comment]
> I like it, it seems to be a security measure we should implement, right?

Yes, not to reveal who uses thoth (origin) and source code usage (especially on private repos).

**Comment by fridex** [comment]
> I would make it minimal invasive: just the API endpoint removed

+1
