### ISSUE TITLE
add adviser version to x-user-api-service-version http header

### ISSUE THREAD

**Issue by goern** [thoth-station/user-api#1163]
**Is your feature request related to a problem? Please describe.**
ssia

**Comment by fridex** [comment]
Not sure if we can to accomplish this, and if this is doable in an easy way. user-api and adviser are loosely coupled components so adviser version is not known to user-api. Moreover, if any of these two components are updated/downgraded the response header will not correspond to adviser results obtained from the service if they might be computed by newer/older advisers. The adviser version is visible in adviser results and user-api acts as a gate for obtaining and scheduling advisers.

**Comment by fridex** [comment]
I will close this one, feel free to reopen if this is required. Thanks for RFE.
