### ISSUE TITLE
Learn about Kebechet managers used in specific repos

### ISSUE THREAD

**Issue by pacospace** [thoth-station/user-api#1181]
**Is your feature request related to a problem? Please describe.**

Currently, we know when a user is installing Kebechet and if it is active or not, so that we can provide services accordingly. 

But we don't have a way to store information about which managers are active. Moreover, if the user deactivates a certain manager would be also interesting to know.

**Comment by pacospace** [comment]
Related-to: https://github.com/thoth-station/metrics-exporter/issues/559
Related-to: https://github.com/thoth-station/kebechet/issues/546

**Comment by KPostOffice** [comment]
https://github.com/thoth-station/thoth-application/blob/master/kebechet/overlays/test/kebechet.yaml

**Comment by pacospace** [comment]
@KPostOffice is this something we can do already?

**Comment by KPostOffice** [comment]
@pacospace This is actually present in storages. We store each manager as a boolean column for the installation. Here is a query which uses it. https://github.com/thoth-station/storages/blob/6cf9c2c05d02c698bb8ad8641146cd1dab582fe6/thoth/storages/graph/postgres.py#L3890
We want to get a count of how many instances of each manager we find in the database right?

**Comment by pacospace** [comment]
> @pacospace This is actually present in storages. We store each manager as a boolean column for the installation. Here is a query which uses it. https://github.com/thoth-station/storages/blob/6cf9c2c05d02c698bb8ad8641146cd1dab582fe6/thoth/storages/graph/postgres.py#L3890 We want to get a count of how many instances of each manager we find in the database right?

should we add a `distinct` in that query? because a slug can have multiple runtime environments right?

**Comment by pacospace** [comment]
> https://github.com/thoth-station/storages/blob/6cf9c2c05d02c698bb8ad8641146cd1dab582fe6/thoth/storages/graph/postgres.py#L3917
> 
> We grab just the first

Sorry, then good :)

**Comment by pacospace** [comment]
> @pacospace This is actually present in storages. We store each manager as a boolean column for the installation. Here is a query which uses it. https://github.com/thoth-station/storages/blob/6cf9c2c05d02c698bb8ad8641146cd1dab582fe6/thoth/storages/graph/postgres.py#L3890 We want to get a count of how many instances of each manager we find in the database right?

Yes, don't we have a query for that?

**Comment by KPostOffice** [comment]
> > @pacospace This is actually present in storages. We store each manager as a boolean column for the installation. Here is a query which uses it. https://github.com/thoth-station/storages/blob/6cf9c2c05d02c698bb8ad8641146cd1dab582fe6/thoth/storages/graph/postgres.py#L3890 We want to get a count of how many instances of each manager we find in the database right?
> 
> Yes, don't we have a query for that?

Yeah you are right. It is right [here](https://github.com/thoth-station/storages/blob/6cf9c2c05d02c698bb8ad8641146cd1dab582fe6/thoth/storages/graph/postgres.py#L3922)

**Comment by pacospace** [comment]
> > > @pacospace This is actually present in storages. We store each manager as a boolean column for the installation. Here is a query which uses it. https://github.com/thoth-station/storages/blob/6cf9c2c05d02c698bb8ad8641146cd1dab582fe6/thoth/storages/graph/postgres.py#L3890 We want to get a count of how many instances of each manager we find in the database right?
> > 
> > 
> > Yes, don't we have a query for that?
> 
> Yeah you are right. It is right [here](https://github.com/thoth-station/storages/blob/6cf9c2c05d02c698bb8ad8641146cd1dab582fe6/thoth/storages/graph/postgres.py#L3922)

Then I think we can close this issue right?
