### ISSUE TITLE
THOTH_JANUSGRAPH_* still required?

### ISSUE THREAD

**Issue by goern** [thoth-station/user-api#122]
Check if user-api still requires THOTH_JANUSGRAPH_PORT and THOTH_JANUSGRAPH_HOST or if they could be removed from templates and configmaps.

**Comment by fridex** [comment]
Yes, we need them at least for the /erase-graph endpoint as of now. Once we will remove pod definitions (for some we will need to supply graph port/host) and the /erase-graph endpoint, we can remove them from templates and keep configuration only in configmap.

**Comment by fridex** [comment]
We also need it for listing environments thus closing this issue.
