### ISSUE TITLE
Parameter 'kebechet_metadata' requires token to be set to perform authenticated request

### ISSUE THREAD

**Issue by harshad16** [thoth-station/user-api#1393]
**Describe the bug**

while trying http://user-api-thoth-test-core.apps.zero.massopen.cloud/api/v1/advise/python?recommendation_type=stable getting this issue:
```
{
  "error": "Parameter 'kebechet_metadata' requires token to be set to perform authenticated request"
}
```

user-api version: v0.24.3

**To Reproduce**
1. Go to `http://user-api-thoth-test-core.apps.zero.massopen.cloud/api/v1/`
2. Click on 'advise'
3. Scroll down to 'response'

**Expected behavior**
successful run with adviser-id

**Comment by harshad16** [comment]
my bad, i forgot to put the token

**Comment by pacospace** [comment]
> my bad, i forgot to put the token

You can also simply remove that key if you want to test without token :)
