### ISSUE TITLE
deprecated endpoint `/qeb-hwt`?

### ISSUE THREAD

**Issue by goern** [thoth-station/user-api#1454]
**Is your feature request related to a problem? Please describe.**
As we deprecate Qeb-Hwt and remove it from the GitHub Marketplace (see https://github.com/thoth-station/kebechet/issues/688 ) we could remove this endpoint.

**Describe the solution you'd like**
remove the endpoint

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

/assign @pacospace

**Comment by pacospace** [comment]
To remove completely we have to: 
- [ ] remove qeb-hwt from user-api
- [ ] remove logic from thoth-common
- [ ] remove logic from workflow-helpers
- [ ] remove logic from investigator
- [ ] remove message from thoth-messaging
- [ ] remote manifests from thoth-application
