### ISSUE TITLE
New dependency graph builder route

### ISSUE THREAD

**Issue by Gkrumbach07** [thoth-station/user-api#1471]
**Is your feature request related to a problem? Please describe.**
I need to visualize and preform analysis on python environment where knowing the dependency graph relations are needed.

**Describe the solution you'd like**
An api route that takes a Pipfile.lock file, calls `pipenv graph`, and returns its results in a (preferably) json structured object.

**Describe alternatives you've considered**
Currently I parse each package's dependency list sourced from its metadata. Then make graph connections for each package and its dependencies. It works but uses a lot of api calls to Thoth to get metadata information.

**Comment by pacospace** [comment]
> **Is your feature request related to a problem? Please describe.**
> I need to visualize and preform analysis on python environment where knowing the dependency graph relations are needed.
> 
> **Describe the solution you'd like**
> An api route that takes a Pipfile.lock file, calls `pipenv graph`, and returns its results in a (preferably) json structured object.
> 
> **Describe alternatives you've considered**
> Currently I parse each package's dependency list sourced from its metadata. Then make graph connections for each package and its dependencies. It works but uses a lot of api calls to Thoth to get metadata information.

Problem with pipenv graph is that it does not give you licences and metadata info, you need to discover those from the API anyways, so maybe we need a post process step on adviser document that store another json file with `adviser-id.dependency_graph` with all informatioin. 

Maybe we can create a `thamos graph` command with some optional parameter to get more info about the packages might be also good to have.

**Comment by KPostOffice** [comment]
`$ pipenv graph` actually requires a venv to be created with all the packages installed. I assume it works by calling `$ python setup.py egg_info` for each dependency and sub-dependency and then reading the generated requirements file. Creating an venv and downloading all dependencies seems too complicated to do in `user-api`

**Comment by Gkrumbach07** [comment]
I see the redundancy now of just having a `pipenv graph` clone for the api. The reason I would still advocate for a new route is that it cuts down on the calls to the api. With very large Pipfile.lock files, numerous calls to the api slow down the UI but not to the point that its unusable.

So the user story here is that a frontend doesn't have to do all the computation for putting together a dependency tree. It leaves that to the backend which is closer to the database.

**Comment by fridex** [comment]
As a solution to your requirement, we can add a dependency graph to the resulting adviser document. The resolver (adviser) has a notion about how the dependencies are structured and can construct a serialized representation of the graph and place it in the resulting JSON document. Would that work for you?

**Comment by Gkrumbach07** [comment]
> Would that work for you?

Yes that would work.

**Comment by goern** [comment]
https://github.com/thoth-station/thoth-application/issues/1496
