### ISSUE TITLE
Add a new in_thoth param to /python/package/versions output

### ISSUE THREAD

**Issue by Gkrumbach07** [thoth-station/user-api#1545]
**Is your feature request related to a problem? Please describe.**
Add if a version of a package is in Thoth or not for the `/python/package/versions` endpoint

**Describe the solution you'd like**
`/python/package/versions` endpoint does not include if the package is available through Thoth. From a UI perspective it is nice to see what a button will do before it is clicked. So when switching versions (in a UI), it is nice to see which versions will result in a 404 and which will show data from Thoth.

Add an extra param to each entry in `versions` to tell if a package is in Thoth or not.

```
{
      "index_url": "https://tensorflow.pypi.thoth-station.ninja/index/manylinux2010/AVX2/simple",
      "package_name": "tensorflow",
      "package_version": "1.7.0rc0",
      "in_thoth": true
}
```

**Describe alternatives you've considered**
the alternative is to grab every metadata of every version, which is a lot of calls to make for packages with many versions.

**Additional context**
For context, a user does not know if these options are supported by Thoth or not. Therefore some may take them to a 404 page.
![image](https://user-images.githubusercontent.com/12587674/146843881-f78011c1-3257-4dd7-99fa-29f719ae4a94.png)

**Comment by fridex** [comment]
Here is a patch proposal to fix this - https://github.com/thoth-station/user-api/pull/1546. The patch exposes only solved packages on Thoth endpoints. I'm not sure if we want to expose unsolved packages - they are internally kept as "to be solved" and users do not need to be aware of the system state in this case. Please let us know your opinion - the endpoint will stay the same but will list only packages known to Thoth.

**Comment by Gkrumbach07** [comment]
@fridex That solution will work.

**Comment by fridex** [comment]
> @fridex That solution will work.

Thanks for the review 👍🏻
