### ISSUE TITLE
Pagination order parameter 

### ISSUE THREAD

**Issue by Gkrumbach07** [thoth-station/user-api#1589]
**Is your feature request related to a problem? Please describe.**
I want to display Python versions of a package using infinite scrolling using the user APIs pagination, however the data is stored from oldest to latest but I would like to display data in the other direction.

**Describe the solution you'd like**
An extra parameter added to pagination endpoints to sort the data before pagination. If the current data array looks like [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] then setting the new param `order="desc"` and `limit=3` for example would return [10, 9, 8]. The default value for `order` would be "asc" or ascending,  returning [1, 2, 3].

**Describe alternatives you've considered**
The alternative is to first do an initial call to the endpoint, which returns the number of elements in the list (disregarding any data provided). Then send subsequent requests using `page=page_count - limit` and `limit=3`. This would give me the values [8, 9, 10]. I then reverse the order of that returned array to get the last 3 elements.

**Comment by fridex** [comment]
> **Is your feature request related to a problem? Please describe.** I want to display Python versions of a package using infinite scrolling using the user APIs pagination, however the data is stored from oldest to latest but I would like to display data in the other direction.
> 
> **Describe the solution you'd like** An extra parameter added to pagination endpoints to sort the data before pagination. If the current data array looks like [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] then setting the new param `order="desc"` and `limit=3` for example would return [10, 9, 8]. The default value for `order` would be "asc" or ascending, returning [1, 2, 3].

OK, I thought the use case is slightly different initially - sorry for the confusion. This approach should be doable with the negative indexing. Asking `per_page=3&page=-1` should give [8, 9, 10]. Is the order important in this case? Assuming the client can use it.

**Comment by Gkrumbach07** [comment]
The order of the elements is important but can easily be reversed client side. Because backwards paging is possible, then there is no issue.
