### ISSUE TITLE
Missing header to expose pagination info

### ISSUE THREAD

**Issue by Gkrumbach07** [thoth-station/user-api#1601]
**Describe the bug**
Pagination was added to the headers of some User API endpoints, however a browser has no access to these headers due to CORS. To get around this, a `Access-Control-Expose-Headers` header needs to be added, or those headers should also be included in  the data object returned in the response.

**Additional context**
Pagination is not optimal without access to these headers due to not knowing the total page count.

**Comment by fridex** [comment]
I'm wondering if we should expose all or just the ones that do pagination by enumerating them. What is your preferred way?

**Comment by Gkrumbach07** [comment]
I cant see a use case where I or anyone else would need all headers. Its easier to access just the pagination data from the data object instead of from the headers. All I really need is the total pages.
