### ISSUE TITLE
Provide more information about container images to users

### ISSUE THREAD

**Issue by fridex** [thoth-station/user-api#1619]
**Is your feature request related to a problem? Please describe.**

As a user of Thoth, I would like to have more information about container images that are listed on the `/container-images` endpoint and `thamos images` listing. 

**Describe the solution you'd like**

Such information might include:

- a (clickable) link to Quay repo where the container image can be found
- a (clickable) link to container image analyses to see what is present in the container image
- a (clickable) link to a view in Thoth Search UI (CC @Gkrumbach07) that shows additional information about container images in a human-readable and easily consumable form (ex. a listing of RPM packages, ABI present, Python interpreter version available, ...)
  - ... see package-extract JSON document for a full listing of available metadata

**Comment by Gkrumbach07** [comment]
https://github.com/thoth-station/search/issues/51 uses the endpoint `search/image/package-extract-220215173550-ce2273bacf3ad91d`

**Comment by fridex** [comment]
Oh, I got confused - I thought a different issue is planned. 

/priority critical-urgent

**Comment by Gkrumbach07** [comment]
@fridex can this be closed? Or is there more information you want in the response body?

**Comment by fridex** [comment]
I'm happy to close this one. Do you want to show this in one of the upcoming demos? It might be a nice feature to show.

**Comment by Gkrumbach07** [comment]
> Do you want to show this in one of the upcoming demos?

Will do!

/kind demo
