### ISSUE TITLE
Add sorting to User API query requests

### ISSUE THREAD

**Issue by Gkrumbach07** [thoth-station/user-api#1670]
**Is your feature request related to a problem? Please describe.**
Some endpoints in User API, specially python versions, would benefit from being sorted. For most cases they are, but every so often they are in a random order. i.e. `boto3`

**Describe the solution you'd like**
A new param to specify if the data should be sorted before paginating and returning a response.

**Describe alternatives you've considered**
Fetch every page and sort client side.

**Additional context**
related: https://github.com/thoth-station/jupyterlab-requirements/issues/620

**Comment by goern** [comment]
@Gkrumbach07 could you put a priority on this and plan it for a release milestone?

**Comment by Gkrumbach07** [comment]
/closed

issue had as merged pr
