### ISSUE TITLE
Remove `count` and `limit` from advise endpoint

### ISSUE THREAD

**Issue by fridex** [thoth-station/user-api#1726]
**Is your feature request related to a problem? Please describe.**

As per discussion in the tech talk, we could drop these two parameters on the advise endpoint. They should be controlled based on the backend configuration rather than allowing users to supply them to the resolution process.

**Describe the solution you'd like**

Remove `count` and `limit` from the advise endpoint. Also, it would be great to make sure that removing these values does not affect scheduling adviser in a deployment negatively (defaults are properly used).

**Comment by codificat** [comment]
For context: tech talk recoding is [here](https://youtu.be/rxq8uhJDPqc).

/triage accepted
/priority important-longterm
/sig user-experience

**Comment by mayaCostantini** [comment]
Closed by #1727
