### ISSUE TITLE
Provide endpoint listing containerized environments for the given package

### ISSUE THREAD

**Issue by fridex** [thoth-station/user-api#1739]
**Is your feature request related to a problem? Please describe.**

As discussed in our last tech talk, let's create an endpoint that will list all containerized environments that provide a package, optionally with a version.

As a Thoth user, I would like to know which containerized environments provide the given package.

As a Thoth user, I would like to know which containerized environments provide the given package-version.

**Comment by fridex** [comment]
Actually, we can have this for all the content in the containerized environment (rpm, python packages, ABI). We have `container-images` endpoint that can list containerized environments this way. CC @Gkrumbach07 feel free to let us know if we should provide any additional functionality on this front.

**Comment by Gkrumbach07** [comment]
Not sure how much more work this would be, but having the ability to input multiple packages (or package-versions) to further refine a query.

**Comment by Gkrumbach07** [comment]
related tech talk: https://www.youtube.com/watch?v=FE-ESrnzD6U

This was for the package viewer page.

This feature is already implmented.

/close
