### ISSUE TITLE
Default value for package import not found

### ISSUE THREAD

**Issue by mayaCostantini** [thoth-station/user-api#1744]
**Describe the bug**
The default value `sklearn.cluster.MiniBatchKMeans` specified in the `/python/imports/` endpoint is not found:
```
{
  "error": "No package name records for package 'sklearn.cluster.MiniBatchKMeans' in database",
  "parameters": {
    "import_name": "sklearn.cluster.MiniBatchKMeans"
  }
}
```
Environment: production.

**To Reproduce**
Go to https://khemenu.thoth-station.ninja/api/v1/ui/#/PythonPackages/get_package_from_imported_packages and query imports for the default value `sklearn.cluster.MiniBatchKMeans` of `import_name`.

**Expected behavior**
Default value is present in the database.

**Comment by harshad16** [comment]
Good catch
The current example `sklearn.cluster.MiniBatchKMeans` doesn't seem to be right import name from scikit-learn , as MiniBatchKMeans can be imported in the following way. 
```
from sklearn.cluster import MiniBatchKMeans
```
so the example should have been `sklearn.cluster`
https://khemenu.thoth-station.ninja/api/v1/python/imports?import_name=sklearn.cluster
