### ISSUE TITLE
Invalid default values for some endpoints

### ISSUE THREAD

**Issue by mayaCostantini** [thoth-station/user-api#1766]
**Describe the bug**

Some API endpoints have default values that result in 40* errors, empty values returned with 20* status code or the API crashing probably because of exceptions not handled in the API logic.
This could cause issues for users wanting to try the API with those default values but also later for security tests we would like to have.

**To Reproduce**

Go to the API on stage / prod environments and execute API requests on those endpoints (for example some /python/package/... endpoints).

**Expected behavior**

Non-empty values are returned with a 20* status code.

**Proposed solution**

- [ ] Find correct default values for the schema
- [ ] Optionally, implement a task that would validate the schema default values on a push event or pull request. This could be useful to replace outdated default values as the data we have will change with time.

**Comment by harshad16** [comment]
@mayaCostantini  can you please give @shreekarSS  some context and getting start help regarding this.
please also evaluate the story point and assign it on the issue title.

**Comment by mayaCostantini** [comment]
@harshad16 sure :+1:

**Comment by shreekarSS** [comment]
**https://khemenu.thoth-station.ninja/api/v1/ui/#/Container%20Images/list_thoth_container_images**
  Expecting list of images in container_images , instead it's in parameters dict
   {
    "container_images": [],
    "parameters": {
	  "cuda_version": "11.1",
	  "image_name": null,
	  "library_name": "/lib64/ld-2.28.so",
	  "os_name": "ubi",
	  "os_version": "9",
	  "package_name": "tensorflow",
	  "page": 0,
	  "per_page": 25,
	  "python_version": "3.9",
	  "rpm_package_name": "ghc-srpm-macros-1.4.2-7.el8.noarch",
	  "symbol": "GLIBC_2.2.5"
    }
  }




**https://khemenu.thoth-station.ninja/api/v1/ui/#/PythonPackages/list_python_packages**
Listing no packages with default values, still 200 response
{
  "packages": [],
  "parameters": {
	"os_name": "ubi",
	"os_version": "9",
	"page": 0,
	"per_page": 25,
	"python_version": "3.9"
  }
}



**https://khemenu.thoth-station.ninja/api/v1/ui/#/PythonPackages/get_python_package_dependencies**
404 Error not found with default value.

{
  "error": "No record found for package 'tensorflow' in version '2.8.0' from index 'https://pypi.org/simple' for 'ubi' in version '9' using Python version '3.9'",
  "parameters": {
	"index": "https://pypi.org/simple",
	"marker_evaluation_result": null,
	"name": "tensorflow",
	"os_name": "ubi",
	"os_version": "9",
	"python_version": "3.9",
	"version": "2.8.0"
  }
}

**https://khemenu.thoth-station.ninja/api/v1/ui/#/PythonPackages/list_python_package_versions**
404 Error not found with default value , expecting to list available python versions
{
  "error": "Package 'tensorflow' not found",
  "parameters": {
	"name": "tensorflow",
	"order_by": null,
	"os_name": "ubi",
	"os_version": "9",
	"python_version": "3.9"
  }
}

**https://khemenu.thoth-station.ninja/api/v1/ui/#/PythonPackages/get_python_package_version_metadata**
Issue: https://github.com/thoth-station/user-api/issues/1771

**Comment by harshad16** [comment]
@shreekarSS  Can please edit your comment into a table for ease of understanding.
https://www.markdownguide.org/extended-syntax/#tables

For Example:


| Endpoint | Errors |  Issue |
|-------------|----------|----------|
| [PythonPackages/get_python_package_version_metadata](https://khemenu.thoth-station.ninja/api/v1/ui/#/PythonPackages/get_python_package_version_metadata)|  Timeout | https://github.com/thoth-station/user-api/issues/1771 |

**Comment by goern** [comment]
noice tracker issue this is! thanks for keeping all the data together. is there any movement on the references issues? what do we need to get them fixed?

**Comment by goern** [comment]
any update on this?

**Comment by shreekarSS** [comment]
> any update on this?

I have some issue with testing apis in the local env. @harshad16 and I are working on that.

**Comment by shreekarSS** [comment]
> Endpoint	Errors	Issue
> [List thoth contaner image](https://khemenu.thoth-station.ninja/api/v1/ui/#/Container%20Images/list_thoth_container_images)	Invalid data	#1780
> [List_python_packages](https://khemenu.thoth-station.ninja/api/v1/ui/#/PythonPackages/list_python_packages)	Data not available	#1782
> [get_python_package_dependencies](https://khemenu.thoth-station.ninja/api/v1/ui/#/PythonPackages/get_python_package_dependencies)	Data not available	#1783
> [list_python_package_versions](https://khemenu.thoth-station.ninja/api/v1/ui/#/PythonPackages/list_python_package_versions)	Data not available	#1784
> [get_python_package_version_metadata](https://khemenu.thoth-station.ninja/api/v1/ui/#/PythonPackages/get_python_package_version_metadata)	Timeout	#1771

All these issues have been fixed , so closing this issue.

**Comment by mayaCostantini** [comment]
Closing as fixed by @shreekarSS
