### ISSUE TITLE
GET api /python/package/version/metadata takes longer time to process in UI

### ISSUE THREAD

**Issue by shreekarSS** [thoth-station/user-api#1771]
**Describe the bug**
The GET api /python/package/version/metadata takes longer to process in the UI (about 120 seconds), but it's relatively quick in the CLI.

**To Reproduce**
hit GET api https://khemenu.thoth-station.ninja/api/v1/ui/#/PythonPackages/get_python_package_version_metadata

**Expected behavior**
API should take lesser time to process in UI similar to the CLI

**Comment by Gkrumbach07** [comment]
/close
Swagger UI is expected to have slower speeds. There is nothing on our end that we can do to improve the speed. Closing b/c no action is needed.
