### ISSUE TITLE
GET api  ​/container-images expecting list of images in container_images , instead it's in parameters dict

### ISSUE THREAD

**Issue by shreekarSS** [thoth-station/user-api#1780]
**Describe the bug**

Expecting list of images in container_images , instead it's in parameters dict
{
  "container_images": [],
  "parameters": {
	"cuda_version": "11.1",
	"image_name": null,
	"library_name": "/lib64/ld-2.28.so",
	"os_name": "ubi",
	"os_version": "9",
	"package_name": "tensorflow",
	"page": 0,
	"per_page": 25,
	"python_version": "3.9",
	"rpm_package_name": "ghc-srpm-macros-1.4.2-7.el8.noarch",
	"symbol": "GLIBC_2.2.5"
  }
}

**To Reproduce**
1. Try https://khemenu.thoth-station.ninja/api/v1/ui/#/Container%20Images/list_thoth_container_images

**Expected behavior**
API should list of images in container_images dict

**Comment by harshad16** [comment]
Based on the issue it seems like 
we are lacking data on the DB for python 3.9 for ubi9

however for the other patterns we do have solutions here:
```
curl -X 'GET' \
  'https://khemenu.thoth-station.ninja/api/v1/container-images?page=0&per_page=25&os_name=ubi&os_version=8&python_version=3.8' \
  -H 'accept: application/json'
```

**Comment by harshad16** [comment]
The issue here is on empty result, instead of 404 data not found,
api is sending the 200 error code.

**Comment by harshad16** [comment]
We are missing the 404 error description for this function:
- [ ] On the openapi front, we can do this by including 404 error pattern in response
https://github.com/thoth-station/user-api/blob/f4b8afeb2acefff64f6b04896a21ae99654b68b9/openapi/openapi.yaml#L680
Ex: [ex](https://github.com/thoth-station/user-api/blob/f4b8afeb2acefff64f6b04896a21ae99654b68b9/openapi/openapi.yaml#L577)
- [ ] On the function side , we are mssing the check if the entries have data.
`if len(entries) >0" at https://github.com/thoth-station/user-api/blob/f4b8afeb2acefff64f6b04896a21ae99654b68b9/thoth/user_api/api_v1.py#L292
Ex: [ex](https://github.com/thoth-station/user-api/blob/f4b8afeb2acefff64f6b04896a21ae99654b68b9/thoth/user_api/api_v1.py#L738)

**Comment by goern** [comment]
what is the status on this?

**Comment by shreekarSS** [comment]
> what is the status on this?

PR is yet get merged
