### ISSUE TITLE
GET ​/python​/package​/dependencies Get direct dependencies of Python libraries: 404 Error 

### ISSUE THREAD

**Issue by shreekarSS** [thoth-station/user-api#1783]
**Describe the bug**
Get api gives 404 Error with  default input values
{
  "error": "No record found for package 'tensorflow' in version '2.8.0' from index 'https://pypi.org/simple' for 'ubi' in version '9' using Python version '3.9'",
  "parameters": {
	"index": "https://pypi.org/simple",
	"marker_evaluation_result": null,
	"name": "tensorflow",
	"os_name": "ubi",
	"os_version": "9",
	"python_version": "3.9",
	"version": "2.8.0"
  }
}

**To Reproduce**
1. Try https://khemenu.thoth-station.ninja/api/v1/ui/#/PythonPackages/get_python_package_dependencies

**Expected behavior**
API should give 200 response with package info

**Comment by goern** [comment]
This seems to require an integration test, right?

/sig devsecops
/priority critical-urgent
/triage accepted

**Comment by harshad16** [comment]
suggestion shared here: https://github.com/thoth-station/user-api/issues/1784#issuecomment-1220282271
would resolve this issue as well.
