### ISSUE TITLE
Graph sync requires frontend namespace configuration

### ISSUE THREAD

**Issue by goern** [thoth-station/user-api#203]
**Describe the bug**
calling `curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' 'http://user-api-thoth-test-core/api/v1/sync?secret=xxx&force_analysis_results_sync=false&force_solver_results_sync=false'` gives

```
{
  "error": "Graph sync requires frontend namespace configuration"
}
```

**To Reproduce**
1. see above 

**Expected behavior**
Graph database get's synced...

**Additional context**

**Comment by fridex** [comment]
This was not closed for some reason - see linked fix.
