### ISSUE TITLE
Remove openapi-spec-validator from Pipfile

### ISSUE THREAD

**Issue by fridex** [thoth-station/user-api#405]
openapi-spec-validator is not our real dependency, but was added to pipfile due to https://github.com/thoth-station/user-api/issues/394

Once resolution will be fixed, we can remove it from Pipfile.

https://github.com/thoth-station/user-api/blob/83da28cbd605830cd59503908830a4c4b574d566/Pipfile#L18

**Comment by goern** [comment]
still valid @fridex ?

**Comment by fridex** [comment]
I don't think so. Let's try it without it.
