### ISSUE TITLE
use cors headers

### ISSUE THREAD

**Issue by goern** [thoth-station/user-api#557]
**Is your feature request related to a problem? Please describe.**
React App cant access user-api due to `Access to XMLHttpRequest at 'http://test.thoth-station.ninja/api/v1/python-package-index' from origin 'http://0.0.0.0:9000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.` 

**Describe the solution you'd like**
Have an ENV Var so that we can set the CORS header of the API

**Describe alternatives you've considered**
completely free CORS by adding a * policy

**Additional context**
This is required for clients consuming the API, running on a different domain.

**Comment by ram-nad** [comment]
I would like to work on this issue. As this API is open for all, it would be best to have 'Access-Control-Allow-Origin: *' policy.

**Comment by ram-nad** [comment]
I would use Flask-cors library for this work.

**Comment by fridex** [comment]
> I would like to work on this issue. As this API is open for all, it would be best to have 'Access-Control-Allow-Origin: *' policy.
> I would use Flask-cors library for this work.

Awesome! The approach sounds good to me. :+1:
