### ISSUE TITLE
Null values in metadata are reported as stringgs

### ISSUE THREAD

**Issue by fridex** [thoth-station/user-api#635]
**Describe the bug**

`null` values are serialized into string `"None"` on Python package metadata endpoint.

**To Reproduce**

Go to our test environment and ask for metadata `setutools`/`38.5.0`/`https://pypi.org/simple`. The response sent back has values of `"None"` (not null, string).

**Expected behavior**

`None` values should not be serialized into a string, but API should report `null` instead.

**Additional context**

This looks like an issue on user-api serialization itself (check openapi.yaml). Data stored in the database look OK.

**Comment by bissenbay** [comment]
@fridex We are actually explicitly saying that string can have a `null` value, for example: [1].
Maybe we should upgrade the version of OpenAPI, :thinking: ? There is a change `Added clarifications to null not being a type (as opposed to a value).` in `OAS 3.0.0-rc1 Released!` [2]

[1] https://github.com/thoth-station/user-api/blob/master/openapi/openapi.yaml#L2037
[2] https://github.com/OAI/OpenAPI-Specification/releases

**Comment by fridex** [comment]
> @fridex We are actually explicitly saying that string can have a `null` value, for example: [1].
> Maybe we should upgrade the version of OpenAPI,  ? There is a change `Added clarifications to null not being a type (as opposed to a value).` in `OAS 3.0.0-rc1 Released!` [2]
> 
> [1] https://github.com/thoth-station/user-api/blob/master/openapi/openapi.yaml#L2037
> [2] https://github.com/OAI/OpenAPI-Specification/releases

You can try to specify `x-nullable` [1] as stated in https://github.com/zalando/connexion/issues/226, but not sure about our thamos client lib generated automatically out of sources (if it supports it). You can also try to set `type: [str, null]`.

[1] https://connexion.readthedocs.io/en/latest/request.html#nullable-parameters

PS: sorry, I accidentally posted this comment to another issue...
