### ISSUE TITLE
reduce log entries

### ISSUE THREAD

**Issue by goern** [thoth-station/user-api#655]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Reduce logging of access to `/metrics`, `/readiness` and `/liveness` so that the log is cleaner. log of level INFO on `alembic.runtime.migration` could also be reset to DEBUG 

**Describe alternatives you've considered**
none

**Additional context**
n/a

**Comment by fridex** [comment]
It could be great to create a generic approach for this - adjust any logger via environment variables - similar to `THOTH_LOG_*`, but not specific to thoth codebase.
