### ISSUE TITLE
User-API deployment fails when PostgreSQL is not setup.

### ISSUE THREAD

**Issue by harshad16** [thoth-station/user-api#791]
**Describe the bug**
User-API deployment fails when PostgreSQL is not set up in the namespace

**To Reproduce**
1. Restart/Remove/ReDeploy PostgreSQL 
2. while the step 1 is executing ReDeploy User-API

**Expected behavior**
User-API should start and serve the endpoint to users

**Error Log**
```
2020-02-18 22:19:28,667  27 INFO     jaeger_tracing:436: opentracing.tracer initialized to <jaeger_client.tracer.Tracer object at 0x7fe70c4d2748>[app_name=user_api]
--
  | 2020-02-18 22:19:28,680  30 INFO     jaeger_tracing:446: Initializing Jaeger Tracer with UDP reporter
  | 2020-02-18 22:19:28,685  30 INFO     jaeger_tracing:384: Using sampler ConstSampler(True)
  | 2020-02-18 22:19:28,690  30 INFO     jaeger_tracing:436: opentracing.tracer initialized to <jaeger_client.tracer.Tracer object at 0x7fe70c4de4e0>[app_name=user_api]
  | 2020-02-18 22:19:31,677  28 ERROR    thoth.user_api.openapi_server:1891: Exception on /readiness [GET]
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2276, in _wrap_pool_connect
  | return fn()
  | File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 303, in unique_connection
  | return _ConnectionFairy._checkout(self)
  | File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 773, in _checkout
  | fairy = _ConnectionRecord.checkout(pool)
  | File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
  | rec = pool._do_get()
  | File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
  | self._dec_overflow()
  | File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
  | compat.reraise(exc_type, exc_value, exc_tb)
  | File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
  | raise value
  | File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
  | return self._create_connection()
  | File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
  | return _ConnectionRecord(self)
  | File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
  | self.__connect(first_connect_check=True)
  | File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 652, in __connect
  | connection = pool._invoke_creator(self)
  | File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
  | return dialect.connect(*cargs, **cparams)
  | File "/opt/app-root/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 489, in connect
  | return self.dbapi.connect(*cargs, **cparams)
  | File "/opt/app-root/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
  | conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
  | psycopg2.OperationalError: FATAL:  password authentication failed for user "thoth"


```

**Comment by harshad16** [comment]
![userapi](https://user-images.githubusercontent.com/14028058/74783769-5d1bac00-5274-11ea-9bb8-a9f5f922e65b.png)

A scenario where PostgreSQL is setup but not initialized.

```
2020-02-18 22:29:52,166  30 WARNING  thoth.common.openshift:144: TLS verification when communicating with k8s/okd master is disabled
--
  | 2020-02-18 22:29:52,292  28 INFO     alembic.runtime.migration:154: Context impl PostgresqlImpl.
  | 2020-02-18 22:29:52,292  28 INFO     alembic.runtime.migration:161: Will assume transactional DDL.
  | 2020-02-18 22:29:52,294  30 INFO     jaeger_tracing:446: Initializing Jaeger Tracer with UDP reporter
  | 2020-02-18 22:29:52,297  28 WARNING  thoth.storages.graph.postgres:261: Database is not ready to receive or query data: Database is not initialized yet
  | 2020-02-18 22:29:52,297  30 INFO     jaeger_tracing:384: Using sampler ConstSampler(True)
  | 2020-02-18 22:29:52,299  28 INFO     alembic.runtime.migration:154: Context impl PostgresqlImpl.
  | 2020-02-18 22:29:52,299  28 INFO     alembic.runtime.migration:161: Will assume transactional DDL.
  | 2020-02-18 22:29:52,300  30 INFO     jaeger_tracing:436: opentracing.tracer initialized to <jaeger_client.tracer.Tracer object at 0x7f4126f2e6a0>[app_name=user_api]
  | 2020-02-18 22:29:52,301  28 WARNING  thoth.user_api:165: Database schema is not initialized
```

**Comment by fridex** [comment]
Awesome, thanks for the report!

As discussed on the call, posting my bits here:

* user-api should start even if pg is down - it can still serve some of its endpoints and there is no reason why our whole application should be down if pg is down
* we use readiness check to check for db schema - that's why its failing - the check was introduced to make sure we talk to the correctly initialized database - so we have a chicken-egg problem here
* the check above can be performed by an operator deploying user-api as a component

**Comment by saisankargochhayat** [comment]
Should we close this?

**Comment by goern** [comment]
from my point of view user-api behaves correct

1. if the database is not reachable -> not ready, as some endpoints need the db
2. if the schema is not in sync with the thoth-storages version used by user-api -> not ready, as data might be corrupt

if there are endpoints that don't need the db, we should thing about moving them out of user-api, as the readiness probe for the service can not distinguish between endpoints requiring the db or those not requiring the db.

I general, the behavior that user-api is not ready if the database is not in a well known and compatible state feels right to me.

**Comment by fridex** [comment]
> I general, the behavior that user-api is not ready if the database is not in a well known and compatible state feels right to me.

Some of the endpoints need a database connection some of them use Ceph to retrieve results from and some of them use OpenShift API.

In general, it is a good practice not to depend on any external pods within the cluster in readiness/liveness probes. If there is a temporary network spike, short database delays or anything similar, it leads to cascaded restarts of pods within the cluster - in this case user facing API.

Readiness probes try to check if the service is ready to receive traffic - if the HTTP server was correctly booted and workers are ready to accept connections. 

Liveness probe checks if the service is responsive - if it is able to receive traffic and respond to users. They try to restart the service if anything on the service level goes wrong (e.g. programming errors like deadlocks, node issue where the pod processes run, ...).

We still can schedule workload (e.g. advises) if the database is down, we can still obtain results of the workload scheduled - I don't see any reason why we should respond with 503 (service unavailable) while some parts (if not the most crucial ones) of the application can still serve user requests without any issues.

**Comment by goern** [comment]
@harshad16 is this still valid?

**Comment by harshad16** [comment]
This should have been fixed. we haven't seen this issue again.
closing it. thanks :+1:
