### ISSUE TITLE
Are github webhook params optional?

### ISSUE THREAD

**Issue by saisankargochhayat** [thoth-station/user-api#799]
The `post_advise_python` states the github params to be optional, however, if anything is missing it returns "Not all webhook parameters provided for GitHub webhook", is this behaviour intended?
[Link](https://github.com/thoth-station/user-api/blob/06bb06dd827918a0bbb569e1c28d1be79e0a9a04/thoth/user_api/api_v1.py#L272)

The Kebechet manager calls thamos advise_here method calls advise without these github params - [[Link](https://github.com/thoth-station/kebechet/blob/c83eeb69bf6f6bb8f41c3380558a59849a25feeb/kebechet/managers/thoth_advise/thoth_advise.py#L149)], which returns that missing param's error from the api.

**Comment by fridex** [comment]
They should be optional. Nice catch! :+1:

**Comment by saisankargochhayat** [comment]
So should we, change the user-api if condition that return's that error?

**Comment by fridex** [comment]
> So should we, change the user-api if condition that return's that error?

Yes, please adjust openapi spec accordingly :+1:
