### ISSUE TITLE
describe test case for scaled up user-api [3pt]

### ISSUE THREAD

**Issue by goern** [thoth-station/user-api#954]
**Is your feature request related to a problem? Please describe.**
If we scale up user-api to more than 1 pod, which endpoints might create data in one pod and access that via a different pod?
Can we creat a test case for such a use case?

**Comment by fridex** [comment]
What data are we considering here?

Related: https://github.com/thoth-station/thoth-application/issues/111

**Comment by fridex** [comment]
I think we can close this and move the discussion to https://github.com/thoth-station/thoth-application/pull/376 Sorry for not noticing this issue before.
