### ISSUE TITLE
Legacy job implementation in user-api that should be replaced with argo related logic [3pt]

### ISSUE THREAD

**Issue by saisankargochhayat** [thoth-station/user-api#965]
The reason behind this is the legacy job implementation in user-api that should be replaced with argo related logic:

https://github.com/thoth-station/user-api/blob/c1b80baae49b90556534f3c5de3c5e47a0c8d530/thoth/user_api/api_v1.py#L798

It should be replaced with get_workflow_status. Mind the difference in the returned dict - they are not easily interchangeable easily.

The same applies for the other status and log endpoints.

_Originally posted by @fridex in https://github.com/thoth-station/thamos/pull/475#issuecomment-659187384_

**Comment by saisankargochhayat** [comment]
- Create a wrapper around [get_workflow_status](https://github.com/thoth-station/common/blob/4152294f4410a943959e9e4e8f903e01d33ee029/thoth/common/openshift.py#L1611) called `get_workflow_status_report`, 
- Call that new method in [get_document](https://github.com/thoth-station/user-api/blob/c1b80baae49b90556534f3c5de3c5e47a0c8d530/thoth/user_api/api_v1.py#L783)
- Change OpenAPI Schema accordingly to to return a shcema similar to - https://github.com/thoth-station/user-api/blob/d3ca6ecd05a8ad2c59870d14255300514b602556/openapi/openapi.yaml#L2043  
 without the `container` , `exit_code` keys

CC @fridex

**Comment by fridex** [comment]
Awesome :+1:
